[package]
name = "mailparse"
version = "0.1.0"
authors = ["Léo Gaspard <leo@gaspard.io>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
console = "0.14.1"
glob = "0.3.0"
indicatif = "0.15.0"
nom = "6.1"
pathfinding = "2.1"
rayon = "1.5"
structopt = "0.3.21"
